/* eslint-disable prettier/prettier */
const strings = {
    appName: "The Fitness Diaries",
    welcomeMessage: "Welcome, ",
    introText: "Track your progress effortlessly",
    workoutsTitle: "Your Workouts",
    addWorkout: "Add Workout",
    editWorkout: "Edit Workout",
    deleteWorkout: "Delete Workout",
    profile: "Profile",
    history: "History",
    home: "Home",
    back: "Back",
    successAddWorkout: "Workout added successfully",
    successUpdateWorkout: "Workout updated successfully",
    successDeleteWorkout: "Workout deleted successfully",
    successAddSession: "Workout session recorded successfully",
    successUpdateSession: "Workout session updated successfully",
    successUpdateWeight: "Weight entry updated successfully",
    successAddWeight: "Weight entry added successfully",
    profileTitle: "My Profile",
    nameLabel: "Name",
    ageLabel: "Age",
    heightLabel: "Height",
    latestWeightLabel: "Latest Weight",
    weightChartLabel: "Weight Progress",
    newWeightLabel: "Add New Weight",
    submitWeightButton: "Save Weight",
};

export default strings;
